package utils

const (
	ErrInvalidJSONFormat          = "Invalid JSON format in the request body."
	ErrErrorCheckingExistence     = "Error checking user existence."
	ErrUserExists                 = "User with this email already exists."
	ErrCouldNotSaveUser           = "Could not save user."
	ErrInvalidCredentials         = "Invalid credentials."
	ErrFailedToGenerateToken      = "Failed to generate authentication token."
	ErrFailedToFetchEvents        = "Failed to fetch events."
	ErrInvalidEventIDFormat       = "Invalid event ID format."
	ErrFailedToFetchEventDetails  = "Failed to fetch event details."
	ErrEventNotFound              = "Event not found."
	ErrUnauthorizedToUpdateEvent  = "Not authorized to update this event."
	ErrUnauthorizedToDeleteEvent  = "Not authorized to delete this event."
	ErrFailedToCancelRegistration = "Failed to cancel event registration."
	ErrInvalidRequestData         = "Invalid request data."
	ErrFailedToCreateEvent        = "Failed to create event."
	ErrNotAuthorizedToUpdateEvent = "Not authorized to update this event."
	ErrNotAuthorizedToDeleteEvent = "Not authorized to delete this event."
	ErrFailedToUpdateEvent        = "Failed to update event."
	ErrFailedToDeleteEvent        = "Failed to delete event."
	ErrEventRegistrationExists    = "event registration already done."
	ErrEventRegistrationNotFound  = "event registration not found."
)
